### PR TITLE
Better things, sorry zach

### PR DESCRIPTION
**Pull request by l3gacyb3ta**
- Open image in new tab by clicking.
- Sorry zach, most of your code is gone

### CODE REVIEW

**Comment by l3gacyb3ta** [comment]
AdD wAtErCsS, iMpRoVe ReSpOnSiVeNeSs, OpEn ImAgE iN nEw TaB
 \- @kognise

**Comment by kognise** [comment]
(maybe don't merge until proper css grid magic is added)

**Comment by zachlatta** [comment]
So awesome. Can’t wait to merge and deploy tomorrow

**Comment by radioblahaj** [comment]
nice

**Pull request merged**
